DROP FUNCTION IF EXISTS public.get_listing_by_slug(text);

CREATE FUNCTION public.get_listing_by_slug(p_slug text)
RETURNS TABLE(
  id uuid, 
  name text, 
  slug text, 
  tier text, 
  description text, 
  short_description text, 
  logo_url text, 
  website text, 
  email text, 
  phone text, 
  country text, 
  county text,
  town_city text,
  postcode text,
  address text, 
  is_active boolean, 
  created_at timestamptz, 
  updated_at timestamptz,
  facebook_url text, 
  instagram_url text, 
  linkedin_url text,
  twitter_url text, 
  youtube_url text,
  tiktok_url text,
  pinterest_url text,
  whatsapp_url text,
  threads_url text,
  latitude numeric, 
  longitude numeric, 
  region_id integer,
  year_established integer,
  employee_count text,
  venue_type text,
  venue_capacity integer,
  capacity integer,
  box_office_phone text,
  contact_name text, 
  contact_email text, 
  contact_phone text, 
  contact_job_title text,
  primary_category_id uuid,
  continent text,
  show_contacts boolean
)
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT 
    l.id,
    l.name,
    l.slug,
    l.tier::text,
    l.description,
    l.short_description,
    l.logo_url,
    l.website,
    l.email,
    l.phone,
    l.country,
    l.county,
    l.town_city,
    l.postcode,
    l.address,
    l.is_active,
    l.created_at,
    l.updated_at,
    l.facebook_url,
    l.instagram_url,
    l.linkedin_url,
    l.twitter_url,
    l.youtube_url,
    l.tiktok_url,
    l.pinterest_url,
    l.whatsapp_url,
    l.threads_url,
    l.latitude,
    l.longitude,
    l.region_id,
    l.year_established,
    l.employee_count,
    l.venue_type,
    l.venue_capacity,
    l.capacity,
    l.box_office_phone,
    l.contact_name,
    l.contact_email,
    l.contact_phone,
    l.contact_job_title,
    l.primary_category_id,
    l.continent,
    l.show_contacts
  FROM listings l
  WHERE l.slug = p_slug
    AND l.is_active = true
  LIMIT 1;
$$;